---
tiny:
  model_path:
    F:\Facultate\Dizertatie\Proiect\models\tiny_model_simplified.onnx
  model_size:
    256
large:
  model_path:
    F:\Facultate\Dizertatie\Proiect\models\large_model_simplified.onnx
  model_size:
    512